CREATE TABLE DM_HangHoa (
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	TenHangHoa NVARCHAR(250),
	DonGia FLOAT CHECK (DonGia >= 0.0),
)

CREATE TABLE PhieuNhap (
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	SoPhieu NVARCHAR(50),
	NgayLapPhieu DATETIME
)

CREATE TABLE PhieuNhapCT (
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	IDPN BIGINT REFERENCES PhieuNhap(ID),
	IDHH BIGINT REFERENCES DM_HangHoa(ID),
	SoLuong INT,
	Gia FLOAT
)
